services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    user: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: student
      RABBITMQ_DEFAULT_PASS: student123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
    network_mode: "service:rabbitmq"
    depends_on:
      rabbitmq:
        condition: service_healthy
